# Generated by Django 5.1.7 on 2025-05-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
        ('users_and_accounts', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_books',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='catalog.book'),
        ),
    ]
